from fastapi import APIRouter, BackgroundTasks, HTTPException
from app.api.schemas import ResearchRequest, ResearchResponse, ResearchResult, ResearchStatus
from app.storage.results_store import create_job, get_job, update_job_result
import uuid
from datetime import datetime
import logging
import asyncio

logger = logging.getLogger(__name__)

router = APIRouter()

@router.post("/research", response_model=ResearchResponse, status_code=202)
async def submit_research(req: ResearchRequest, background_tasks: BackgroundTasks):
    """Submit a research job. Returns a job ID for polling."""
    job_id = str(uuid.uuid4())
    create_job(job_id, req.topic)
    
    background_tasks.add_task(run_research_job_mock, job_id, req.topic)
    
    return ResearchResponse(
        id=job_id,
        status=ResearchStatus.PENDING,
        created_at=datetime.utcnow()
    )

@router.get("/research/{job_id}", response_model=ResearchResult)
async def get_research(job_id: str):
    """Get the status and result of a research job."""
    job = get_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Research job not found")
    return job

async def run_research_job_mock(job_id: str, topic: str):
    """Run the research with mock data (no API calls)."""
    try:
        update_job_result(job_id, "running")
        logger.info(f"Starting mock research job {job_id} on topic: {topic}")
        
        # Simulate agent work with delays
        await asyncio.sleep(3)  # Simulate Researcher agent
        
        await asyncio.sleep(2)  # Simulate Analyst agent
        
        await asyncio.sleep(2)  # Simulate Writer agent
        
        await asyncio.sleep(1)  # Simulate Reviewer agent
        
        # Generate mock report
        mock_report = f"""# Research Report: {topic}

## Executive Summary
This is a simulated research report generated by the Multi-Agent Research Assistant system.

The system successfully:
- Received your research query
- Deployed 4 specialised agents (Researcher, Analyst, Writer, Reviewer)
- Processed the request asynchronously
- Generated this structured report

## Key Findings

### Finding 1: System Architecture
The multi-agent system uses CrewAI orchestration with:
- **Researcher Agent**: Gathers information from sources
- **Analyst Agent**: Synthesises findings into themes
- **Writer Agent**: Produces professional reports
- **Reviewer Agent**: Validates quality and citations

### Finding 2: Production Readiness
The system includes:
- FastAPI REST API with Swagger documentation
- Async background job processing
- SQLite database for job storage
- Structured logging and error handling
- Modular, production-ready code structure

### Finding 3: Next Steps
To enable real research with LLMs:
1. Add an OpenAI API key to `.env`
2. Or use Ollama for local, free inference
3. Or use Groq's free tier

## Conclusion
The Multi-Agent Research Assistant system is fully functional and ready to be connected to an LLM provider. All architecture, routing, storage, and agent orchestration are working correctly.

---
*Report generated on: {datetime.utcnow().isoformat()}*
*Job ID: {job_id}*
*Status: MOCK MODE - No LLM API calls were made*"""
        
        # Save the result
        update_job_result(job_id, "completed", report=mock_report)
        logger.info(f"Mock research job {job_id} completed successfully")
        
    except Exception as e:
        logger.error(f"Mock research job {job_id} failed: {str(e)}")
        update_job_result(job_id, "failed", error=str(e))